# Generated by Django 5.1.2 on 2026-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables-fruits', 'Vegetables & Fruits'), ('dairy-bread', 'Dairy & Bread'), ('snacks-drinks', 'Snacks & Drinks'), ('meat-fish', 'Meat & Fish'), ('cleaning', 'Cleaning'), ('bath-body', 'Bath & Body'), ('paper-goods', 'Paper Goods'), ('pet-care', 'Pet Care')], default='dairy-bread', max_length=50),
        ),
    ]
